FoodBank/urls.py
from django.urls import path
from .views import (
    cart_add,
    corp_register,
    user_login,
    user_register,
    main,
    payment,
    item_clear,
    item_decrement,
    item_increment,
    cart_clear,
    cart_detail,
    thank_you,
    log_out,
)

app_name = "FoodBank"

urlpatterns = [
    path("", user_login, name="login"),
    path("register/", user_register, name="register"),
    path("register/corp", corp_register, name="corp_register"),
    path("main/", main, name="main"),
    path("payment/", payment, name="payment"),
    path("cart/add/<int:id>/", cart_add, name="cart_add"),
    path("cart/item_clear/<int:id>/", item_clear, name="item_clear"),
    path("cart/item_increment/<int:id>/", item_increment, name="item_increment"),
    path("cart/item_decrement/<int:id>/", item_decrement, name="item_decrement"),
    path("cart/cart_clear/", cart_clear, name="cart_clear"),
    path("cart/cart-detail/", cart_detail, name="cart_detail"),
    path("thank", thank_you, name="thank_you"),
    path("logout/", log_out, name="logout"),
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from FoodBank import views
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("FoodBank.urls")),
    path("payment/paymenthandler/", views.paymenthandler, name="paymenthandler"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FoodBank/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    mobile = models.CharField(max_length=10, unique=True)
    pan = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.user.username


class CorpInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    mobile = models.CharField(max_length=10, unique=True)
    pan = models.CharField(max_length=10, unique=True)
    tan = models.CharField(max_length=10, unique=True)
    url = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return self.user.username


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    image = models.ImageField(upload_to="images/")

    def __str__(self):
        return self.name


class Donation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    date = models.DateField(auto_now=True)

    def __str__(self):
        return self.user.username

FoodBank/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import Donation, Product, User, UserInfo, CorpInfo
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
import razorpay
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.urls import reverse
from cart.cart import Cart


# Create your views here.


def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        print(username, password)
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse("FoodBank:main"))
        else:
            print("HEllo")
            return render(request, "firstpage.html")
    return render(request, "firstpage.html")


def user_register(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        email = request.POST.get("email")
        mobile = request.POST.get("phone")
        pan = request.POST.get("pan")
        user = User(username=username, password=password, email=email)
        user.set_password(user.password)
        user.save()
        userinfo = UserInfo(user=user, mobile=mobile, pan=pan)
        userinfo.save()
        return HttpResponseRedirect(reverse("FoodBank:main"))
    return render(request, "regindi.html")


def corp_register(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        email = request.POST.get("email")
        # mobile = request.POST.get("phone")
        pan = request.POST.get("pan")
        tan = request.POST.get("tan")
        url = request.POST.get("url")
        user = User(username=username, password=password, email=email)
        user.set_password(user.password)
        user.save()

        userinfo = CorpInfo(user=user, pan=pan, tan=tan, url=url)
        userinfo.save()
        return HttpResponseRedirect(reverse("FoodBank:main"))
    return render(request, "regcorp.html")


@login_required
def main(request):
    products = Product.objects.all()
    return render(request, "Food-front.html", {"products": products})


# authorize razorpay client with API Keys.
razorpay_client = razorpay.Client(
    auth=(settings.RAZOR_KEY_ID, settings.RAZOR_KEY_SECRET)
)


@login_required
def payment(request):
    currency = "INR"
    amount = 0  # Rs. 200
    # Create a Razorpay Order
    cart = Cart(request)
    for key, value in cart.cart.items():
        amount += int(value["price"]) * int(value["quantity"])
    print(amount * 10)
    amount *= 100
    razorpay_order = razorpay_client.order.create(
        dict(amount=amount, currency=currency, payment_capture="0")
    )

    # order id of newly created order.
    razorpay_order_id = razorpay_order["id"]
    callback_url = "paymenthandler/"

    # we need to pass these details to frontend.
    context = {}
    context["razorpay_order_id"] = razorpay_order_id
    context["razorpay_merchant_key"] = settings.RAZOR_KEY_ID
    context["razorpay_amount"] = amount
    context["currency"] = currency
    context["callback_url"] = callback_url

    return render(request, "cartSum.html", context=context)


# we need to csrf_exempt this url as
# POST request will be made by Razorpay
# and it won't have the csrf token.
@csrf_exempt
def paymenthandler(request):

    # only accept POST request.
    if request.method == "POST":
        try:

            # get the required parameters from post request.
            payment_id = request.POST.get("razorpay_payment_id", "")
            razorpay_order_id = request.POST.get("razorpay_order_id", "")
            signature = request.POST.get("razorpay_signature", "")
            params_dict = {
                "razorpay_order_id": razorpay_order_id,
                "razorpay_payment_id": payment_id,
                "razorpay_signature": signature,
            }

            # verify the payment signature.
            result = razorpay_client.utility.verify_payment_signature(params_dict)
            if result is None:
                amount = 20000  # Rs. 200
                try:

                    # capture the payemt
                    razorpay_client.payment.capture(payment_id, amount)
                    # add cart to donations
                    cart = Cart(request)
                    for key, value in cart.cart.items():
                        d = Donation(
                            user=request.user,
                            product=value["product"],
                            quantity=value["quantity"],
                        )
                        d.save()
                    # render success page on successful caputre of payment
                    return render(request, "paymentsuccess.html")
                except:

                    # if there is an error while capturing payment.
                    return render(request, "paymentfail.html")
            else:
                print("hey")
                # if signature verification fails.
                return render(request, "paymentfail.html")
        except:
            print("hello")
            # if we don't find the required parameters in POST data
            return HttpResponseBadRequest()
    else:
        # if other than POST request is made.
        return HttpResponseBadRequest()


@login_required()
def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("FoodBank:main")


@login_required()
def item_clear(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect("cart_detail")


@login_required()
def item_increment(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("FoodBank:payment")


@login_required()
def item_decrement(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.decrement(product=product)
    return redirect("FoodBank:payment")


@login_required()
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("cart_detail")


@login_required()
def cart_detail(request):
    return render(request, "cart/cart_detail.html")


def thank_you(request):
    return render(request, "thankyou.html")


def log_out(request):
    logout(request)
    return redirect("FoodBank:main")

FoodBank/templates/foodbank/Food-front.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script
      data-require="jquery@3.1.1"
      data-semver="3.1.1"
      src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"
    ></script>
    <!-- <link rel="stylesheet" href="style.css" /> -->
    <!-- <script src="script.js"></script> -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Food Donation</title>
    <link
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
    />
    <!-- <link rel=".stylesheet" href="../../static/css/Food-front.css"> -->
    <style>
      body {
        padding: 0%;
        margin: 0%;
        box-sizing: border-box;
        /* background-image: url("https://i.pinimg.com/originals/6c/b4/d6/6cb4d65f510cfe685777815e670627a8.jpg"); */
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
      }

      header nav {
        /* border: 1px solid white; */
        width: 100vw;
        height: 8vh;
        display: flex;
        position: fixed;
        justify-content: space-between;
        z-index: 1;
        background: rgba(0, 0, 0, 0.5);
        box-shadow: 0px 0px 7px rgba(0, 0, 0, 0.4);
        overflow: hidden;
      }
      header nav div {
        margin-left: 60%;
        margin-right: 5%;
        /* border: 1px solid white; */
        width: 50%;
        opacity: 1;
        height: 100%;
        display: flex;
        align-items: center;
        justify-content: space-around;
      }
      header nav a {
        border: none;
        background: none;
        color: rgb(255, 255, 255);
        padding: 8px;
        font-weight: 100;
        text-decoration: none;
      }
      header nav a:hover {
        border: 0px;
        background: rgb(217, 139, 29);
        color: white;
        transition: 0.2s linear;
        border-radius: 40px;
        padding: 8px;
        cursor: pointer;
        box-shadow: 0px 5px 50px white;
      }
      body {
        padding: 0%;
        margin: 0%;
        box-sizing: border-box;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
      }

      header nav {
        /* border: 1px solid white; */
        width: 100vw;
        height: 8vh;
        display: flex;
        position: fixed;
        justify-content: flex-end;
        z-index: 1;
        background-color: orange;
        box-shadow: 0px 0px 7px rgba(0, 0, 0, 0.4);
        overflow: hidden;
      }
      header nav div {
        margin-left: 60%;
        margin-right: 5%;
        /* border: 1px solid white; */
        width: 50%;
        opacity: 1;
        height: 100%;
        display: flex;
        align-items: center;
        justify-content: space-around;
      }
      header nav a {
        border: none;
        background: none;
        color: rgb(255, 255, 255);
        padding: 8px;
        font-weight: 100;
        text-decoration: none;
      }
      header nav a:hover {
        border: 0px;
        background: rgb(217, 139, 29);
        color: white;
        transition: 0.2s linear;
        border-radius: 40px;
        padding: 8px;
        cursor: pointer;
        box-shadow: 0px 5px 50px white;
      }
      .main {
        display: flex;
        flex-direction: row;
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(230px, 1fr));
        grid-gap: 20px;
      }
      /* .food-item-name{
        height: 20px;
      } */
      .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        max-width: 300px;
        height: fit-content;
        text-align: center;
        font-family: arial;
        border-radius: 50px;
        cursor: pointer;
        margin: auto;
        display: grid;
        grid-template-rows: max-content 50px 1fr;
      }
      select {
        appearance: none;

        background-color: transparent;
        border: none;
        padding: 0 1em 0 0;
        margin: 0;
        width: 100%;
        font-family: inherit;
        font-size: inherit;
        cursor: inherit;
        line-height: inherit;
      }
      select::-ms-expand {
        display: none;
      }
      select {
        outline: none;
      }
      .price {
        color: grey;
        font-size: 22px;
      }
      .img-id {
        width: 100%;
        height: 156px;
      }
      .card a {
        border: none;
        outline: 0;
        padding: 12px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 90%;
        font-size: 18px;
        border-radius: 20px;
        text-decoration: none;
      }

      #qt-txt {
        margin-right: 30px;
      }
      .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
      }
      /* .quantity{
              display: flex;
              margin-left: 2cm;

        } */
      .quantity {
        display: inline-block;
      }

      .quantity .input-text.qty {
        width: 35px;
        height: 39px;
        padding: 0 5px;
        text-align: center;
        background-color: transparent;
        border: 1px solid #efefef;
      }

      .quantity.buttons_added {
        text-align: left;
        position: relative;
        white-space: nowrap;
        vertical-align: top;
      }

      .quantity.buttons_added input {
        display: inline-block;
        margin: 0;
        vertical-align: top;
        box-shadow: none;
      }

      .quantity.buttons_added .minus,
      .quantity.buttons_added .plus {
        padding: 7px 10px 8px;
        height: 41px;
        background-color: #ffffff;
        border: 1px solid #efefef;
        cursor: pointer;
      }

      .quantity.buttons_added .minus {
        border-right: 0;
      }

      .quantity.buttons_added .plus {
        border-left: 0;
      }

      .quantity.buttons_added .minus:hover,
      .quantity.buttons_added .plus:hover {
        background: #eeeeee;
      }

      .quantity input::-webkit-outer-spin-button,
      .quantity input::-webkit-inner-spin-button {
        -webkit-appearance: none;
        -moz-appearance: none;
        margin: 0;
      }

      .quantity.buttons_added .minus:focus,
      .quantity.buttons_added .plus:focus {
        outline: none;
      }
      i {
        color: #000;
      }
    </style>
  </head>
  <body>
    <header>
      <nav>
        <div>
          <a href="{% url 'FoodBank:payment' %}"
            ><i class="fa fa-shopping-cart fa-lg" aria-hidden="true"></i
          ></a>
          <!-- <a href="#">Who we are</a>
          <a href="#">Why we exist</a>
          <a href="#">What we do</a>
          <a href="#">Our team</a> -->
          <a href="{% url 'FoodBank:logout' %}">Log Out</a>
        </div>
      </nav>
    </header>
    <br /><br /><br /><br />
    <div class="main">
      {% for product in products %}
      <div class="card">
        <img src="{{product.image.url}}" alt="Food Image" style="width: 100%" />
        <div class="food-item-name">
          <h1>{{product.name}}</h1>
        </div>
        <p class="price">{{product.price}} Rs</p>

        <h4 id="qt-txt">Quantity</h4>
        <span>
          <div class="quantity buttons_added">
            <input type="button" value="-" class="minus" /><input
              type="number"
              step="1"
              min="1"
              max=""
              name="quantity"
              value="1"
              title="Qty"
              class="input-text qty text"
              size="4"
              pattern=""
              inputmode=""
            /><input type="button" value="+" class="plus" />
          </div>
        </span>
        <p>
          <a href="{% url 'FoodBank:cart_add' product.id %}">Add to Cart</a>
        </p>
      </div>
      {% endfor %}
    </div>
  </body>
  <script>
    function wcqib_refresh_quantity_increments() {
      jQuery(
        "div.quantity:not(.buttons_added), td.quantity:not(.buttons_added)"
      ).each(function (a, b) {
        var c = jQuery(b);
        c.addClass("buttons_added"),
          c
            .children()
            .first()
            .before('<input type="button" value="-" class="minus" />'),
          c
            .children()
            .last()
            .after('<input type="button" value="+" class="plus" />');
      });
    }
    String.prototype.getDecimals ||
      (String.prototype.getDecimals = function () {
        var a = this,
          b = ("" + a).match(/(?:\.(\d+))?(?:[eE]([+-]?\d+))?$/);
        return b
          ? Math.max(0, (b[1] ? b[1].length : 0) - (b[2] ? +b[2] : 0))
          : 0;
      }),
      jQuery(document).ready(function () {
        wcqib_refresh_quantity_increments();
      }),
      jQuery(document).on("updated_wc_div", function () {
        wcqib_refresh_quantity_increments();
      }),
      jQuery(document).on("click", ".plus, .minus", function () {
        var a = jQuery(this).closest(".quantity").find(".qty"),
          b = parseFloat(a.val()),
          c = parseFloat(a.attr("max")),
          d = parseFloat(a.attr("min")),
          e = a.attr("step");
        (b && "" !== b && "NaN" !== b) || (b = 0),
          ("" !== c && "NaN" !== c) || (c = ""),
          ("" !== d && "NaN" !== d) || (d = 0),
          ("any" !== e &&
            "" !== e &&
            void 0 !== e &&
            "NaN" !== parseFloat(e)) ||
            (e = 1),
          jQuery(this).is(".plus")
            ? c && b >= c
              ? a.val(c)
              : a.val((b + parseFloat(e)).toFixed(e.getDecimals()))
            : d && b <= d
            ? a.val(d)
            : b > 0 && a.val((b - parseFloat(e)).toFixed(e.getDecimals())),
          a.trigger("change");
      });
  </script>
</html>

FoodBank/templates/foodbank/cartSum.html
<!DOCTYPE html>
{% load static %}
{% load cart_tag %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cart Summary</title>
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
</head>

<body>
    <div class="container">
        <div class="heading">
            <h1>
                <span class="shopper">s</span> Shopping Cart
            </h1>

            <a href="#" class="visibility-cart transition is-open">X</a>
        </div>

        <div class="cart transition is-open">

            <!-- <a href="#" class="btn btn-update">Update cart</a> -->


            <div class="table">

                <div class="layout-inline row th">
                    <div class="col col-pro">Product</div>
                    <div class="col col-price align-center ">
                        Price
                    </div>
                    <div class="col col-qty align-center">QTY</div>
                    <div class="col">Total</div>
                </div>

                <div class="layout-inline row">

                    {% for key,value in request.session.cart.items %}
                    <div class="col col-pro layout-inline">
                        <img src="{{value.image}}" alt="kitten" />
                        <p>{{value.name}}</p>
                    </div>

                    <div class="col col-price col-numeric align-center ">
                        <p>{{value.price}}</p>
                    </div>

                    <div class="col col-qty layout-inline">
                        <a href="{% url 'FoodBank:item_decrement' value.product_id %}"  class="qty qty-minus">-</a>
                        <input type="numeric" value="{{value.quantity}}" />
                        <a href="{% url 'FoodBank:item_increment' value.product_id %}" class="qty qty-plus">+</a>
                    </div>
                    <div class="col col-total col-numeric">
                        <p>{{value.price|multiply:value.quantity}}</p>
                    </div>
                    {% endfor %}
            </div>

            <a href="" class="btn btn-update" id="pay-btn">Donate❤️</a>

        </div>


</body>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
  <script>

    // add event listener to the payment button.
    document.getElementById("pay-btn").onclick = function (e) {
        var options = {
      // Enter the Key ID generated from the Dashboard
      key: "{{ razorpay_merchant_key }}",

      // Amount is in currency subunits.
      // Default currency is INR. Hence,
      // 50000 refers to 50000 paise
      amount: "{{ razorpay_amount }}",
      currency: "{{ currency }}",

      // Your/store name.
      name: "Bangalore Food Bank",

      // Pass the `id` obtained in the response of Step 1
      order_id: "{{ razorpay_order_id }}",
      callback_url: "{{ callback_url }}",
    };
        // initialise razorpay with the options.
        var rzp1 = new Razorpay(options);
      rzp1.open();
      e.preventDefault();
    };
  </script>
</html>

FoodBank/templates/foodbank/firstpage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/foodBank.css' %}" />
    <title>Document</title>
    <script
      src="https://kit.fontawesome.com/8d60853972.js"
      crossorigin="anonymous"
    ></script>
  </head>

  <body>
    <header>
      <nav>
        <div class="login_menu">
          <a href="{% url 'FoodBank:register' %}" id="individual" type="login"
            >Register as Individual</a
          >
          <a href="{% url 'FoodBank:corp_register' %}" id="corporate"
            >Register as Corporate</a
          >
          <a href="{% url 'admin:index' %}" id="admin">Admin</a>
        </div>
      </nav>
    </header>
    <main>
      <div class="logo">
        <div class="orgName">FOOD BANK</div>
      </div>
    </main>
    <section class="data">
      <div id="about" class="division">
        <div class="about">
          <div class="about-text">
            <h2>About Us</h2>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Accusamus, temporibus fugit placeat illum eaque eos est voluptas
              minus vel nostrum rem molestiae aut dolores iusto architecto esse
              aperiam ipsam eum quia dicta natus, mollitia vero qui. Obcaecati
              maiores quo corporis fuga dolores totam voluptas voluptate, ipsa
              esse ducimus ab eos labore sunt sapiente! Reiciendis, mollitia!
              Tempore!
            </p>
          </div>
        </div>
        <div class="form">
          <form action="{% url 'FoodBank:login' %}" method="POST">
            {% csrf_token %}
            <input
              type="text"
              name="username"
              placeholder="username"
              required
            />
            <br /><br />
            <input
              type="password"
              name="password"
              placeholder="password"
              required
            />
            <br />
            <button type="submit">login</button>
          </form>
        </div>
      </div>
      <div id="vision-mission" class="division">
        <div class="vision child">
          <h2>Our Vision</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus,
            temporibus fugit placeat illum eaque eos est voluptas minus vel
            nostrum rem molestiae aut dolores iusto architecto esse aperiam
            ipsam eum quia dicta natus, mollitia vero qui. Obcaecati maiores quo
            corporis fuga dolores totam voluptas voluptate, ipsa esse ducimus ab
            eos labore sunt sapiente! Reiciendis, mollitia! Tempore!
          </p>
        </div>
        <div class="mission child">
          <h2>Our Mission</h2>
          <ul class="list-type">
            <li>
              To create a supportive environment that will address the issues of
              hunger and malnutrition
            </li>
            <li>
              To improve nutritional interventions by reinforcing the
              interaction between the various actors in the programme
            </li>
            <li>
              To develop a sustainable system that ends food wastage at all
              levels of its supply chain from harvest to the consumption phase
            </li>
            <li>
              To mobilize various resources and to build a culture of
              innovations to accomplish zero hunger
            </li>
            <li>
              To create and promote nationwide awareness and to lend a voice to
              those who are not heard
            </li>
          </ul>
        </div>
      </div>
    </section>
    <footer>
      <section id="contact">
        <h1 class="section-heading mb50px">
          <span> Contact </span>
        </h1>
        <div id="contact-container">
          <div id="contact-form-container">
            <form id="contact-form">
              <input
                id="input-name"
                name="name"
                type="text"
                placeholder="Your Name"
              />
              <input
                id="input-email"
                name="input-email"
                type="text"
                required
                placeholder="Your Email"
              />
              <textarea
                id="input-message"
                name="input-message"
                rows="2"
                cols="40"
                placeholder="Message"
              ></textarea>
              <br />
              <button class="sub-btn" type="submit">SEND MESSAGE</button>
            </form>
          </div>
          <div id="my-details-container" style="color: white">
            <h3>Get In touch</h3>
            <p>
              Lorem Ipsum has been the industry's standard dummy text ever since
              the 1500s, when an unknown printer took a galley of type and
              scrambled it to make a type specimen book.
            </p>

            <h3>My Address</h3>
            <div class="my-details-info-container">
              <i class="fas fa-map-marker-alt"></i>
              <span>Delhi, India</span>
            </div>
            <div class="my-details-info-container">
              <i class="fas fa-mobile-alt"></i>
              <span>9999999999</span>
            </div>
            <div class="my-details-info-container">
              <i class="far fa-envelope"></i>
              <span>myemail@gmail.com</span>
            </div>
          </div>
        </div>

        <div class="text-center social-icons">
          <ul class="no-list-style horizontal-list">
            <li>
              <a
                href="https://plus.google.com/u/0/103030702784925512939"
                target="_blank"
              >
                <i class="fab fa-google-plus-g"></i>
              </a>
            </li>

            <li>
              <a href="https://www.facebook.com/manishakhattar54">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>

            <li>
              <a
                href="https://www.quora.com/profile/Manisha-Khattar"
                target="_blank"
              >
                <i class="fab fa-quora"></i>
              </a>
            </li>
          </ul>
          <p>©️ Copyright 2020-21 Bangalore Food Bank All Rights Reserved</p>
        </div>
      </section>
    </footer>
  </body>
</html>

FoodBank/templates/foodbank/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Index</title>
  </head>
  <body>
    Hello World!
  </body>
</html>